// ============================================================
//  家庭点菜 — 纯本地版
//  IndexedDB 存储 · 密码保护 · 微信分享同步
//  零服务器 · 零注册 · 永久免费
// ============================================================

const DC=[{name:'凉菜',emoji:'🧊'},{name:'热菜',emoji:'🍳'},{name:'汤类',emoji:'🍲'},{name:'主食',emoji:'🍚'},{name:'饮品',emoji:'🥤'}];
const DM=[{name:'爸爸',a:''},{name:'妈妈',a:''},{name:'爷爷',a:''},{name:'奶奶',a:''},{name:'大宝',a:''},{name:'小宝',a:''}];
const DD=[{id:1,n:'拍黄瓜',c:'凉菜',p:12,e:'🥒',img:'',d:'清爽脆嫩'},{id:2,n:'凉拌木耳',c:'凉菜',p:15,e:'🍄',img:'',d:'爽口开胃'},{id:3,n:'皮蛋豆腐',c:'凉菜',p:14,e:'🥚',img:'',d:'嫩滑豆腐'},{id:4,n:'口水鸡',c:'凉菜',p:28,e:'🍗',img:'',d:'麻辣鲜香'},{id:5,n:'酱牛肉',c:'凉菜',p:32,e:'🥩',img:'',d:'酱香浓郁'},{id:6,n:'糖拌西红柿',c:'凉菜',p:10,e:'🍅',img:'',d:'酸甜清爽'},{id:7,n:'红烧排骨',c:'热菜',p:38,e:'🦴',img:'',d:'软烂入味'},{id:8,n:'鱼香肉丝',c:'热菜',p:26,e:'🐟',img:'',d:'酸甜微辣'},{id:9,n:'宫保鸡丁',c:'热菜',p:28,e:'🐔',img:'',d:'花生脆香'},{id:10,n:'糖醋里脊',c:'热菜',p:30,e:'🍖',img:'',d:'外酥里嫩'},{id:11,n:'麻婆豆腐',c:'热菜',p:18,e:'🧈',img:'',d:'麻辣下饭'},{id:12,n:'清炒时蔬',c:'热菜',p:16,e:'🥬',img:'',d:'清淡健康'},{id:13,n:'回锅肉',c:'热菜',p:28,e:'🥓',img:'',d:'肥而不腻'},{id:14,n:'干煸四季豆',c:'热菜',p:18,e:'🫘',img:'',d:'干香微辣'},{id:15,n:'番茄炒蛋',c:'热菜',p:15,e:'🍳',img:'',d:'国民家常'},{id:16,n:'番茄蛋花汤',c:'汤类',p:12,e:'🥣',img:'',d:'清淡鲜美'},{id:17,n:'酸辣汤',c:'汤类',p:14,e:'🌶️',img:'',d:'酸辣开胃'},{id:18,n:'排骨玉米汤',c:'汤类',p:25,e:'🌽',img:'',d:'清甜滋补'},{id:19,n:'紫菜蛋花汤',c:'汤类',p:10,e:'🫧',img:'',d:'简单鲜美'},{id:20,n:'白米饭',c:'主食',p:3,e:'🍚',img:'',d:'香喷喷'},{id:21,n:'蛋炒饭',c:'主食',p:12,e:'🍛',img:'',d:'粒粒分明'},{id:22,n:'手工水饺',c:'主食',p:22,e:'🥟',img:'',d:'皮薄馅大'},{id:23,n:'番茄鸡蛋面',c:'主食',p:14,e:'🍜',img:'',d:'家常味'},{id:24,n:'馒头',c:'主食',p:2,e:'🥖',img:'',d:'松软'},{id:25,n:'可乐',c:'饮品',p:5,e:'🥤',img:'',d:'冰爽'},{id:26,n:'雪碧',c:'饮品',p:5,e:'🧊',img:'',d:'清爽'},{id:27,n:'橙汁',c:'饮品',p:8,e:'🍊',img:'',d:'鲜榨'},{id:28,n:'王老吉',c:'饮品',p:6,e:'🫖',img:'',d:'怕上火'},{id:29,n:'酸梅汤',c:'饮品',p:5,e:'🫗',img:'',d:'消暑'}];

// === IndexedDB ===
function idb(){return new Promise((r,j)=>{const q=indexedDB.open('fmDB',1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains('s'))d.createObjectStore('s');};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});}
async function g(k){const d=await idb();return new Promise((r,j)=>{const t=d.transaction('s','readonly'),o=t.objectStore('s'),q=o.get(k);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});}
async function s(k,v){const d=await idb();return new Promise((r,j)=>{const t=d.transaction('s','readwrite'),o=t.objectStore('s'),q=o.put(v,k);q.onsuccess=()=>r();q.onerror=()=>j(q.error);});}
function cp(o){return JSON.parse(JSON.stringify(o));}

// === 状态 ===
let M=[],C=[],P=[],O=[],cart=[],cur='all',sr='',cm='dishes',ni=1000,tDI='',tMA='';

// === 密码 ===
async function chkPin(){const p=await g('pin');if(!p){document.getElementById('lockNew').style.display='block';document.getElementById('lockEnter').style.display='none';}else{document.getElementById('lockNew').style.display='none';document.getElementById('lockEnter').style.display='block';}ss('lockScreen');}
async function setPin(){const a=document.getElementById('pin1').value.trim(),b=document.getElementById('pin2').value.trim();if(!a)return;if(a!==b){toast('两次不一致');return;}await s('pin',a);await se();start();}
async function enterPin(){const a=document.getElementById('pin3').value.trim(),b=await g('pin'),e=document.getElementById('pinErr');if(a!==b){e.textContent='密码错误';e.classList.add('show');return;}e.classList.remove('show');start();document.getElementById('pin3').value='';}
async function chP(){const v=document.getElementById('np').value.trim();if(!v){toast('请输入新密码');return;}await s('pin',v);document.getElementById('np').value='';toast('✅ 已修改');}
async function resetAll(){if(!confirm('⚠️ 重置密码会清空所有数据！确定？'))return;const d=await idb();const t=d.transaction('s','readwrite'),o=t.objectStore('s');o.clear();await new Promise(r=>{t.oncomplete=r;});location.reload();}
async function se(){const u=await g('menu');if(!u){await s('menu',DD);await s('cats',DC);await s('mems',DM);await s('orders',[]);}}

// === 启动 ===
async function start(){M=await g('menu')||cp(DD);C=await g('cats')||cp(DC);const rm=await g('mems');P=(rm&&typeof rm[0]==='string')?rm.map(n=>({name:n,a:''})):(rm||cp(DM));O=await g('orders')||[];let ns=false,mx=0;M.forEach(d=>{if(!d.id){d.id=++mx;ns=true;}else if(d.id>mx)mx=d.id;});ni=mx>=999?mx+1:1000;if(ns)await s('menu',M);const ids=new Set(M.map(d=>d.id));cart=(await g('cart')||[]).filter(c=>ids.has(c.id));ss('mainScreen');rA();}

// === 渲染 ===
function ss(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');}
function rA(){rMS();rCN();rMG();rCB();rCP();rH();rMD();rMC();rMM();}
function rMS(){const el=document.getElementById('ms'),v=el.value;el.innerHTML='<option value="">-- 选择家人 --</option>'+P.filter(m=>m.name).map(m=>`<option value="${esc(m.name)}">${esc(m.name)}</option>`).join('');if(P.some(m=>m.name===v))el.value=v;onMC();}
function onMC(){const m=P.find(x=>x.name===document.getElementById('ms').value);document.getElementById('ma').innerHTML=m&&m.a?`<img src="${m.a}">`:'👤';}
function rCN(){document.getElementById('cn').innerHTML='<button class="cat-btn active" data-cat="all">🔥 全部</button>'+C.map(c=>`<button class="cat-btn" data-cat="${esc(c.name)}">${c.emoji} ${esc(c.name)}</button>`).join('');}
function rMG(){const g=document.getElementById('mg');let d=M;if(cur!=='all')d=d.filter(x=>x.c===cur);if(sr){const k=sr.toLowerCase();d=d.filter(x=>(x.n||'').toLowerCase().includes(k));}if(!d.length){g.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:50px;color:var(--text-light);"><p style="font-size:3rem;">🔍</p><p>没有找到</p></div>';return;}const bs=['#fef5e7','#fdecea','#edf7f0','#e8f4fd','#fdf2f8','#f5f0e8','#e8f8f5','#fef9e7'];g.innerHTML=d.map(dd=>{const ic=cart.find(c=>c.id===dd.id),q=ic?ic.q:0;return`<div class="menu-card"><div class="menu-card-img" style="${dd.img?'':'background:'+bs[Math.abs(dd.id)%bs.length]}">${dd.img?`<img src="${dd.img}" loading="lazy">`:dd.e||'🍽️'}</div><div class="menu-card-body"><div class="menu-card-name">${esc(dd.n)}</div><div class="menu-card-desc">${esc(dd.d)}</div><div class="menu-card-footer"><div class="menu-card-price"><span class="unit">¥</span>${dd.p}</div>${q>0?`<div class="menu-card-qty"><button onclick="event.stopPropagation();cQ(${dd.id},-1)">−</button><span class="qty-num">${q}</span><button onclick="event.stopPropagation();cQ(${dd.id},1)">+</button></div>`:`<button class="menu-card-add" onclick="event.stopPropagation();aT(${dd.id})">+</button>`}</div></div></div>`;}).join('');}
function fM(){sr=document.getElementById('si').value.trim();rMG();}

// === 购物车 ===
function aT(id){const d=M.find(x=>x.id===id);if(!d)return;const m=document.getElementById('ms').value;if(!m){toast('⚠️ 请选点菜人');return;}const ex=cart.find(c=>c.id===id&&c.m===m);if(ex)ex.q++;else cart.push({id,name:d.n,price:d.p,emoji:d.e,img:d.img||'',q:1,m});s('cart',cart);rMG();rCB();rCP();}
function cQ(id,d){const m=document.getElementById('ms').value,it=cart.find(c=>c.id===id&&c.m===m);if(!it)return;it.q+=d;if(it.q<=0)cart=cart.filter(c=>!(c.id===id&&c.m===m));s('cart',cart);rMG();rCB();rCP();}
function cCQ(id,mb,d){const it=cart.find(c=>c.id===id&&c.m===mb);if(!it)return;it.q+=d;if(it.q<=0)cart=cart.filter(c=>!(c.id===id&&c.m===mb));s('cart',cart);rMG();rCB();rCP();}
function tC(){return cart.reduce((s,c)=>s+c.q,0);}
function tP(){return cart.reduce((s,c)=>s+c.price*c.q,0);}
function rCB(){const c=tC(),b=document.getElementById('cb');b.textContent=c;b.style.display=c>0?'flex':'none';}
function tC(){const p=document.getElementById('cp'),o=document.getElementById('co');if(p.classList.contains('open'))lC();else{rCP();o.classList.add('open');p.classList.add('open');}}
function lC(){document.getElementById('co').classList.remove('open');document.getElementById('cp').classList.remove('open');}
function rCP(){const l=document.getElementById('cl'),e=document.getElementById('ce'),f=document.getElementById('cf');if(!cart.length){l.innerHTML='';l.style.display='none';e.style.display='flex';f.classList.remove('show');}else{l.style.display='block';e.style.display='none';f.classList.add('show');l.innerHTML=cart.map(c=>`<div class="cart-item"><div class="cart-item-img">${c.img?`<img src="${c.img}">`:c.emoji||'🍽️'}</div><div class="cart-item-info"><div class="cart-item-name">${esc(c.name)}</div><div class="cart-item-member">👤 ${esc(c.m)}</div><div class="cart-item-price">¥${c.price*c.q}</div></div><div class="cart-item-qty"><button onclick="cCQ(${c.id},'${escJs(c.m)}',-1)">−</button><span>${c.q}</span><button onclick="cCQ(${c.id},'${escJs(c.m)}',1)">+</button></div></div>`).join('');}document.getElementById('cc').textContent=tC();document.getElementById('ct').textContent=tP();}

// === 订单 ===
function sO(){if(!cart.length){toast('⚠️ 购物车空');return;}const g={};cart.forEach(c=>{if(!g[c.m])g[c.m]=[];g[c.m].push(c);});let h='';for(const[m,items]of Object.entries(g)){h+=`<p style="font-weight:600;margin:12px 0 4px;">👤 ${esc(m)}</p><ul class="confirm-list">`;items.forEach(c=>{h+=`<li><span class="dish-info"><span class="confirm-item-img">${c.img?`<img src="${c.img}">`:c.emoji||'🍽️'}</span>${esc(c.name)} ×${c.q}</span><span style="color:var(--primary);font-weight:600;">¥${c.price*c.q}</span></li>`;});h+='</ul>';}h+=`<div class="confirm-total">合计：<span>¥${tP()}</span></div>`;document.getElementById('cmb').innerHTML=h;document.getElementById('com').classList.add('open');}
function lM(){document.getElementById('com').classList.remove('open');}
async function cO(){const n=document.getElementById('cnote').value.trim();O.unshift({id:Date.now(),time:new Date().toLocaleString('zh-CN'),items:[...cart],total:tP(),note:n});cart=[];document.getElementById('cnote').value='';await s('cart',cart);await s('orders',O);lC();lM();rCB();rCP();rH();toast('🎉 下单成功');}
function rH(){const l=document.getElementById('hl');if(!O.length){l.innerHTML='<div class="history-empty"><p>📋</p><p>暂无订单</p></div>';return;}l.innerHTML=O.map(o=>{const t=(o.items||[]).map(c=>`<span class="history-tag">${c.img?'🖼️':c.emoji||'🍽️'} ${esc(c.name)}×${c.q}</span>`).join(''),ms=[...new Set((o.items||[]).map(c=>c.m))].join('、');return`<div class="history-card"><div class="history-card-header"><span>📅 ${o.time}</span><span>👤 ${esc(ms)}</span></div><div class="history-card-dishes">${t}</div>${o.note?`<div class="order-note">📝 ${esc(o.note)}</div>`:''}<div class="history-card-footer">¥${o.total}</div></div>`;}).join('');}
async function clH(){if(!O.length)return;if(!confirm('清空全部订单？'))return;O=[];await s('orders',O);rH();toast('🗑️ 已清空');}

// === Tab ===
function sT(t){document.querySelectorAll('#mc .tab').forEach(x=>x.classList.remove('active'));document.getElementById(t+'Tab')?.classList.add('active');if(t==='manage'){rMD();rMC();rMM();}if(t==='history')rH();window.scrollTo({top:0,behavior:'smooth'});}

// === 管理渲染 ===
function rMD(){const l=document.getElementById('mdl');document.getElementById('dc').textContent=`共 ${M.length} 道菜`;if(!M.length){l.innerHTML='<div class="history-empty"><p>🍽️</p><p>暂无菜品</p></div>';return;}const g={};M.forEach(d=>{if(!g[d.c])g[d.c]=[];g[d.c].push(d);});let h='';for(const[c,ds]of Object.entries(g)){const ce=(C.find(x=>x.name===c)||{}).emoji||'📂';h+=`<p style="font-weight:700;margin:16px 0 6px;font-size:0.9rem;color:var(--text-light);">${ce} ${esc(c)} (${ds.length})</p>`;ds.forEach(d=>{h+=`<div class="manage-dish-item"><div class="manage-dish-thumb">${d.img?`<img src="${d.img}">`:d.e||'🍽️'}</div><div class="manage-dish-info"><div class="manage-dish-name">${esc(d.n)}</div><div class="manage-dish-meta"><span class="cat-tag">${esc(d.c)}</span>${esc(d.d)}</div></div><div class="manage-dish-price">¥${d.p}</div><div class="manage-dish-actions"><button class="btn-icon-sm" onclick="oD(${d.id})">✏️</button><button class="btn-icon-sm danger" onclick="delD(${d.id})">🗑️</button></div></div>`;});}l.innerHTML=h;}
function rMC(){const l=document.getElementById('mcl');if(!C.length){l.innerHTML='<div class="history-empty"><p>📂</p><p>暂无分类</p></div>';return;}l.innerHTML=C.map(c=>`<div class="manage-cat-item"><div class="manage-cat-emoji">${esc(c.emoji)}</div><div class="manage-cat-info"><div class="manage-cat-name">${esc(c.name)}</div><div class="manage-cat-count">${M.filter(d=>d.c===c.name).length} 道</div></div><div class="manage-cat-actions"><button class="btn-icon-sm" onclick="oC('${escJs(c.name)}')">✏️</button><button class="btn-icon-sm danger" onclick="delC('${escJs(c.name)}')">🗑️</button></div></div>`).join('');}
function rMM(){const l=document.getElementById('mml');if(!P.length){l.innerHTML='<div class="history-empty"><p>👨‍👩‍👧‍👦</p><p>暂无家人</p></div>';return;}const av=['👨','👩','👴','👵','👦','👧','🧑','👶','🧒'];l.innerHTML=P.map((m,i)=>`<div class="manage-member-item"><div class="manage-member-avatar">${m.a?`<img src="${m.a}">`:av[i%av.length]}</div><div class="manage-member-name">${esc(m.name)}</div><div class="manage-member-actions"><button class="btn-icon-sm" onclick="oM('${escJs(m.name)}')">✏️</button><button class="btn-icon-sm danger" onclick="delM('${escJs(m.name)}')">🗑️</button></div></div>`).join('');}

// === 图片 ===
function ci(f,mw,mh,q){return new Promise((r,j)=>{if(!f.type.startsWith('image/'))return j(new Error('非图片'));const fr=new FileReader();fr.onload=e=>{const img=new Image();img.onload=()=>{let w=img.width,h=img.height;if(w>mw){h*=mw/w;w=mw;}if(h>mh){w*=mh/h;h=mh;}const c=document.createElement('canvas');c.width=Math.round(w);c.height=Math.round(h);c.getContext('2d').drawImage(img,0,0,c.width,c.height);r(c.toDataURL('image/jpeg',q));};img.onerror=()=>j(new Error('加载失败'));img.src=e.target.result;};fr.onerror=()=>j(new Error('读取失败'));fr.readAsDataURL(f);});}

// === 菜品 CRUD ===
function oD(id){tDI='';document.getElementById('dcat').innerHTML=C.map(c=>`<option value="${esc(c.name)}">${c.emoji} ${esc(c.name)}</option>`).join('');if(id){const d=M.find(x=>x.id===id);if(!d)return;document.getElementById('dt').textContent='✏️ 编辑';document.getElementById('di').value=d.id;document.getElementById('dn').value=d.n;document.getElementById('dcat').value=d.c;document.getElementById('dpr').value=d.p;document.getElementById('de').value=d.e;document.getElementById('dde').value=d.d;document.getElementById('dep').textContent=d.e||'🥘';if(d.img){tDI=d.img;document.getElementById('dp').innerHTML=`<img src="${d.img}">`;document.getElementById('dp').classList.add('has-image');document.getElementById('dcb').style.display='inline-block';}else clD();}else{document.getElementById('dt').textContent='🍽️ 添加';document.getElementById('di').value='';['dn','de','dde'].forEach(x=>document.getElementById(x).value='');document.getElementById('dpr').value='';document.getElementById('dcat').value=C[0]?.name||'';document.getElementById('dep').textContent='🥘';clD();}document.getElementById('dm').classList.add('open');}
async function hD(e){const f=e.target.files[0];if(!f)return;try{tDI=await ci(f,400,300,0.7);document.getElementById('dp').innerHTML=`<img src="${tDI}">`;document.getElementById('dp').classList.add('has-image');document.getElementById('dcb').style.display='inline-block';}catch(er){toast('⚠️ '+er.message);}e.target.value='';}
function clD(){document.getElementById('dp').innerHTML='<span class="image-placeholder">🥘</span>';document.getElementById('dp').classList.remove('has-image');document.getElementById('dcb').style.display='none';tDI='';}
function clDM(){document.getElementById('dm').classList.remove('open');}
async function sD(){const id=document.getElementById('di').value,n=document.getElementById('dn').value.trim(),cat=document.getElementById('dcat').value,pr=parseInt(document.getElementById('dpr').value),em=document.getElementById('de').value.trim(),desc=document.getElementById('dde').value.trim();if(!n){toast('⚠️ 请输入菜名');return;}if(!cat){toast('⚠️ 请选分类');return;}if(isNaN(pr)||pr<0){toast('⚠️ 请输入价格');return;}if(id){const d=M.find(x=>x.id===parseInt(id));d.n=n;d.c=cat;d.p=pr;d.e=em||'🍽️';d.d=desc||n;d.img=tDI;}else{M.push({id:ni++,n,cat,p:pr,e:em||'🍽️',img:tDI,d:desc||n});}await s('menu',M);clDM();rMD();rMG();rCN();toast('✅ 已保存');}
async function delD(id){const d=M.find(x=>x.id===id);if(!d||!confirm(`删除「${d.n}」？`))return;M=M.filter(x=>x.id!==id);cart=cart.filter(c=>c.id!==id);await s('menu',M);await s('cart',cart);rMD();rMG();rCN();rCB();rCP();toast('🗑️ '+d.n);}

// === 分类 CRUD ===
function oC(on){if(on){const c=C.find(x=>x.name===on);if(!c)return;document.getElementById('catt').textContent='✏️ 编辑';document.getElementById('coid').value=on;document.getElementById('cnm').value=on;document.getElementById('cem').value=c.emoji;document.getElementById('cep').textContent=c.emoji||'📂';}else{document.getElementById('catt').textContent='📂 添加';document.getElementById('coid').value='';document.getElementById('cnm').value='';document.getElementById('cem').value='';document.getElementById('cep').textContent='📂';}document.getElementById('catm').classList.add('open');}
function clCM(){document.getElementById('catm').classList.remove('open');}
async function sC(){const on=document.getElementById('coid').value.trim(),nn=document.getElementById('cnm').value.trim(),em=document.getElementById('cem').value.trim();if(!nn){toast('⚠️ 请输入名称');return;}if(on){const c=C.find(x=>x.name===on);if(on!==nn&&C.some(x=>x.name===nn)){toast('⚠️ 已存在');return;}c.name=nn;c.emoji=em||'📂';M.forEach(d=>{if(d.c===on)d.c=nn;});await s('menu',M);}else{if(C.some(x=>x.name===nn)){toast('⚠️ 已存在');return;}C.push({name:nn,emoji:em||'📂'});}await s('cats',C);clCM();rMC();rMD();rMG();rCN();toast('✅ 已保存');}
async function delC(n){const ct=M.filter(d=>d.c===n).length;if(!confirm(`删除「${n}」？${ct>0?`\n${ct}道菜将移到其他分类`:''}`))return;C=C.filter(c=>c.name!==n);const fb=C[0]?.name||'';M.forEach(d=>{if(d.c===n)d.c=fb;});await s('cats',C);await s('menu',M);rMC();rMD();rMG();rCN();toast('🗑️ '+n);}

// === 成员 CRUD ===
function oM(on){tMA='';if(on){const m=P.find(x=>x.name===on);if(!m)return;document.getElementById('memt').textContent='✏️ 编辑';document.getElementById('moid').value=on;document.getElementById('mnm').value=on;if(m.a){tMA=m.a;document.getElementById('map').innerHTML=`<img src="${m.a}">`;document.getElementById('map').classList.add('has-image');document.getElementById('mab').style.display='inline-block';}else clM();}else{document.getElementById('memt').textContent='👤 添加';document.getElementById('moid').value='';document.getElementById('mnm').value='';clM();}document.getElementById('memm').classList.add('open');}
async function hM(e){const f=e.target.files[0];if(!f)return;try{tMA=await ci(f,200,200,0.7);document.getElementById('map').innerHTML=`<img src="${tMA}">`;document.getElementById('map').classList.add('has-image');document.getElementById('mab').style.display='inline-block';}catch(er){toast('⚠️ '+er.message);}e.target.value='';}
function clM(){document.getElementById('map').innerHTML='<span class="avatar-placeholder">👤</span>';document.getElementById('map').classList.remove('has-image');document.getElementById('mab').style.display='none';tMA='';}
function clMM(){document.getElementById('memm').classList.remove('open');}
async function sM(){const on=document.getElementById('moid').value.trim(),nn=document.getElementById('mnm').value.trim();if(!nn){toast('⚠️ 请输入称呼');return;}if(on){const i=P.findIndex(x=>x.name===on);if(i===-1||(on!==nn&&P.some(x=>x.name===nn))){toast('⚠️ 已存在');return;}P[i].name=nn;P[i].a=tMA;cart.forEach(c=>{if(c.m===on)c.m=nn;});await s('cart',cart);}else{if(P.some(x=>x.name===nn)){toast('⚠️ 已存在');return;}P.push({name:nn,a:tMA});}await s('mems',P);clMM();rMM();rMS();rCP();toast('✅ 已保存');}
async function delM(n){if(!confirm(`删除「${n}」？`))return;P=P.filter(m=>m.name!==n);cart=cart.filter(c=>c.m!==n);await s('mems',P);await s('cart',cart);rMM();rMS();rCB();rCP();toast('🗑️ '+n);}

// === 导出/导入/恢复 ===
function exp(){const d={menu:M,cats:C,mems:P};const j=JSON.stringify(d),b=new Blob([j],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=`家庭点菜_${new Date().toLocaleDateString('zh-CN').replace(/\//g,'-')}.json`;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{document.body.removeChild(a);URL.revokeObjectURL(url);},1000);toast('📥 下载已触发，查看浏览器下载栏');}
async function cpy(){const d={menu:M,cats:C,mems:P};const j=JSON.stringify(d);try{await navigator.clipboard.writeText(j);toast('📋 已复制！微信发给家人→对方在备份页→📂导入');}catch(e){toast('⚠️ 复制失败，请用下载方式');}}
async function imp(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async ev=>{try{const d=JSON.parse(ev.target.result);if(!d.menu)throw new Error('格式错误');let md=d.mems||[];if(md.length&&typeof md[0]==='string')md=md.map(n=>({name:n,a:''}));if(!confirm(`导入：🍽️${d.menu.length}道菜 📂${(d.cats||[]).length}个分类 👤${md.length}位家人\n\n⚠️ 覆盖当前数据？`)){e.target.value='';return;}M=d.menu;C=d.cats||[];P=md;ni=M.length?Math.max(...M.map(x=>x.id||0),999)+1:1000;await s('menu',M);await s('cats',C);await s('mems',P);rA();rMD();rMC();rMM();toast('✅ 导入成功');}catch(er){toast('⚠️ 文件格式错误');}};r.readAsText(f);e.target.value='';}
async function rst(){if(!confirm('⚠️ 恢复默认？所有自定义数据（含图片）将丢失！'))return;M=cp(DD);C=cp(DC);P=cp(DM);ni=1000;await s('menu',M);await s('cats',C);await s('mems',P);rA();rMD();rMC();rMM();toast('🔄 已恢复');}

// === 工具 ===
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2000);}
function esc(s){const d=document.createElement('div');d.textContent=s||'';return d.innerHTML;}
function escJs(s){return(s||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");}

// === 事件 ===
document.addEventListener('DOMContentLoaded',()=>{
  document.getElementById('cn').addEventListener('click',e=>{const b=e.target.closest('.cat-btn');if(!b)return;document.querySelectorAll('#cn .cat-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');cur=b.dataset.cat;rMG();});
  document.getElementById('mn').addEventListener('click',e=>{const b=e.target.closest('.subnav-btn');if(!b)return;document.querySelectorAll('#mn .subnav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');cm=b.dataset.m;document.querySelectorAll('.manage-panel').forEach(p=>p.classList.remove('active'));document.getElementById('mp'+cm.charAt(0).toUpperCase()+cm.slice(1))?.classList.add('active');if(cm==='dishes')rMD();if(cm==='categories')rMC();if(cm==='members')rMM();});
  document.getElementById('de')?.addEventListener('input',function(){document.getElementById('dep').textContent=this.value||'🥘';});
  document.getElementById('cem')?.addEventListener('input',function(){document.getElementById('cep').textContent=this.value||'📂';});
  document.getElementById('pin3')?.addEventListener('keydown',e=>{if(e.key==='Enter')enterPin();});
  chkPin();
});
